[package]
name = "z3"
version = "0.2.0"
authors = ["Graydon Hoare <graydon@pobox.com>", "Bruce Mitchener <bruce.mitchener@gmail.com>"]

description = "High-level rust bindings for the Z3 SMT solver from Microsoft Research"
license = "MIT"
keywords = ["FFI", "SMT", "satisfiability", "solver"]
categories = ["api-bindings"]
readme = "README.md"
documentation = "https://docs.rs/z3/"
homepage = "https://github.com/endoli/z3.rs"
repository = "https://github.com/endoli/z3.rs.git"

[dependencies]
libc = "0.2"
log = "0.3"
lazy_static = "0.1"
env_logger = "0.3"

[dev-dependencies]
semver = "~0.2.1"

[dependencies.z3-sys]
path = "../z3-sys"
version = "0.2.0"
