[package]
name = "z3-sys"
version = "0.5.0"
authors = ["Graydon Hoare <graydon@pobox.com>", "Bruce Mitchener <bruce.mitchener@gmail.com>"]

description = "Low-level rust-bindgen bindings for the Z3 SMT solver from Microsoft Research"
license = "MIT"
links = "z3"
keywords = ["FFI", "SMT", "satisfiability", "solver"]
categories = ["external-ffi-bindings"]
readme = "README.md"
documentation = "https://docs.rs/z3-sys/"
homepage = "https://github.com/prove-rs/z3.rs"
repository = "https://github.com/prove-rs/z3.rs.git"

[build-dependencies]
cmake = { version = "0.1", optional = true }

[features]
# Enable this feature to statically link our own build of Z3, rather than
# dynamically linking to the system's `libz3.so`.
static-link-z3 = ["cmake"]
